"""GENERATED by scripts/gen_uiengine_catalog.py — do not edit by hand.

Signatures of the UIEngine.* functions the browser-side Kirun runtime
exports (nocode-ui/ui-app/client/src/functions/all.ts). Consumed by
_conventions.UIENGINE_PRIMITIVES (name set) and get_kirun_primitive
(signature lookup). Re-generate when nocode-ui changes.
"""
from __future__ import annotations

from typing import Any

UIENGINE_SIGNATURES: dict[str, dict[str, Any]] = {
    'BuildLeadAdData': {'description': 'Builds the adData object (gclid/wbraid/gbraid/fbc/fbp) for lead-form submissions '
                    'from URL params + Meta Pixel cookies. Persists click identifiers to first-party '
                    'cookies so they survive navigation between landing and form pages.',
     'documentation': '# UIEngine.BuildLeadAdData\n'
                      '\n'
                      'Reads ad-click identifiers from `window.location` query params and browser '
                      'cookies, persists newly-seen ones into first-party cookies, and emits an '
                      '`adData` object suitable for sending alongside a lead-form POST to '
                      '`entity-processor`. The downstream Meta CAPI / Google Conversions API '
                      'dispatchers read these exact keys off the ticket.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      'None.\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Emits the built object\n'
                      '  - `adData` (Any): Object containing whichever of these keys are present: '
                      '`gclid`, `wbraid`, `gbraid`, `fbc`, `fbp`. Empty object `{}` if none are '
                      'detected.\n'
                      '\n'
                      '## Sources, in order\n'
                      '\n'
                      'For each click identifier (`gclid`, `wbraid`, `gbraid`, `fbclid`):\n'
                      '1. Look in the current URL query string. If found, write to a first-party '
                      'cookie (`lz_<name>`, max-age 1 year) so the value survives navigation to a '
                      'separate form page.\n'
                      '2. Else, read from the `lz_<name>` first-party cookie.\n'
                      '\n'
                      'Meta cookies come straight from the browser:\n'
                      '- `fbp` <- cookie `_fbp` (set by Meta Pixel on every page load).\n'
                      '- `fbc` <- cookie `_fbc` (set by Meta Pixel when URL contains `fbclid`); else '
                      'built from the persisted fbclid as `fb.1.<now>.<fbclid>` per Meta CAPI spec.\n'
                      '\n'
                      '## Use\n'
                      '\n'
                      'Bind the output through `UIEngine.SetStore` into a `Page.adData` path, then '
                      'include `Page.adData` in the lead-form POST body sent to '
                      '`/api/entity/processor/entry/website`.',
     'events': {'output': ['adData']},
     'parameters': {},
     'source': 'ui-app/client/src/functions/BuildLeadAdData.ts'},
    'CopyTextToClipboard': {'description': 'Copies the specified text to the system clipboard',
     'documentation': '# UIEngine.CopyTextToClipboard\n'
                      '\n'
                      'Copies the specified text to the system clipboard using the Clipboard API '
                      '(`navigator.clipboard.writeText`). Requires a secure context (HTTPS) in most '
                      'browsers.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **text** (String, required): The text content to copy to the clipboard\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful copy\n'
                      '- **error**: Triggered if the clipboard operation fails\n'
                      '  - `data` (Any): Error details\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Share Links**: Copy shareable URLs to clipboard\n'
                      '- **Copy Codes**: Copy referral codes, verification codes, or API keys\n'
                      '- **Export Data**: Quick copy of formatted text or data\n'
                      '- **Developer Tools**: Copy generated snippets or configuration',
     'events': {'error': ['data']},
     'parameters': {'text': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/CopyTextToClipboard.ts'},
    'DecodeURIComponent': {'description': 'Decodes a URI-encoded string back to its original form',
     'documentation': '# UIEngine.DecodeURIComponent\n'
                      '\n'
                      "Decodes a URI component string using JavaScript's native `decodeURIComponent()` "
                      'function. Converts percent-encoded characters back to their original form.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **uriComponent** (String, required): The URI-encoded string to decode\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered with the decoded result\n'
                      '  - `decodedValue` (String): The decoded string\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **URL Parsing**: Decode values extracted from URL parameters\n'
                      '- **Display Values**: Convert encoded strings for user-friendly display\n'
                      '- **Data Processing**: Decode incoming encoded data from external sources\n'
                      '- **Deep Link Handling**: Decode parameters from shared URLs',
     'events': {'output': ['decodedValue']},
     'parameters': {'uriComponent': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/DecodeURIComponent.ts'},
    'DeleteData': {'description': 'Sends an HTTP DELETE request to remove data at the specified URL',
     'documentation': '# UIEngine.DeleteData\n'
                      '\n'
                      'Makes an HTTP DELETE request to the specified URL with configurable query '
                      'parameters, path parameters, and headers. Used to delete resources on the '
                      'server. Automatically resolves parameter and header values from store '
                      'expressions.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **url** (String, required): The endpoint URL to send the DELETE request to\n'
                      '- **queryParams** (UrlParameters, optional): Key-value pairs appended as query '
                      'string parameters to the URL\n'
                      '- **pathParams** (UrlParameters, optional): Key-value pairs substituted into '
                      'path placeholders in the URL\n'
                      '- **headers** (UrlParameters, optional): HTTP request headers\n'
                      '  - Default includes `Authorization` (from `LocalStore.AuthToken`) and '
                      '`clientCode` (from `Store.auth.loggedInClientCode`)\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful response\n'
                      '  - `data` (Any): The response body from the server\n'
                      '- **error**: Triggered on request failure\n'
                      '  - `data` (Any): Error response body\n'
                      '  - `headers` (Any): Error response headers\n'
                      '  - `status` (Number): HTTP status code\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Record Deletion**: Remove individual records from the database\n'
                      '- **Bulk Cleanup**: Delete resources matching specific criteria\n'
                      '- **Cache Invalidation**: Clear server-side caches\n'
                      '- **Session Termination**: End active sessions or revoke tokens',
     'events': {'error': ['data', 'headers', 'status'], 'output': ['data']},
     'parameters': {'headers': {'hasDefault': True, 'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'pathParams': {'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'queryParams': {'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'url': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/DeleteData.ts'},
    'EncodeURIComponent': {'description': 'Encodes a string as a URI component for safe use in URLs',
     'documentation': '# UIEngine.EncodeURIComponent\n'
                      '\n'
                      "Encodes a URI component string using JavaScript's native `encodeURIComponent()` "
                      'function. Escapes special characters so the string can be safely used as a URL '
                      'parameter value.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **uriComponent** (String, required): The string to encode\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered with the encoded result\n'
                      '  - `encodedValue` (String): The URL-encoded string\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **URL Building**: Safely encode parameter values for URL construction\n'
                      '- **Query Strings**: Encode user input before adding to query parameters\n'
                      '- **API Calls**: Encode values for REST API URL segments\n'
                      '- **Deep Linking**: Encode complex values for shareable URLs',
     'events': {'output': ['encodedValue']},
     'parameters': {'uriComponent': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/EncodeURIComponent.ts'},
    'ExecuteJSFunction': {'description': 'Dynamically executes a named JavaScript function with provided parameters',
     'documentation': '# UIEngine.ExecuteJSFunction\n'
                      '\n'
                      'Dynamically executes a JavaScript function by name with provided parameters. '
                      'Uses the Function constructor to invoke the named function, allowing '
                      'integration with global JavaScript functions or third-party libraries.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **name** (String, required): The fully qualified JavaScript function name to '
                      'execute (e.g., `console.log`, `Math.round`)\n'
                      '- **params** (Any[], required): Array of parameters to pass to the function\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful execution\n'
                      '  - `result` (Any): The return value from the executed function\n'
                      '- **error**: Triggered if the function execution fails\n'
                      '  - `data` (Any): Error details\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Third-Party Integration**: Call functions from external JavaScript '
                      'libraries\n'
                      '- **Custom Logic**: Execute custom JavaScript functions defined in the global '
                      'scope\n'
                      '- **Dynamic Computation**: Perform calculations using built-in JavaScript '
                      'functions\n'
                      '- **Legacy Integration**: Interface with existing JavaScript codebases',
     'events': {'error': ['data'], 'output': ['result']},
     'parameters': {'name': {'type': 'string'}, 'params': {'ref': 'System.any', 'type': 'ref'}},
     'source': 'ui-app/client/src/functions/ExecuteJSFunction.ts'},
    'FetchData': {'description': 'Fetches data from the specified URL with given parameters and headers',
     'documentation': '# UIEngine.FetchData\n'
                      '\n'
                      'Makes an HTTP GET request to the specified URL with configurable query '
                      'parameters, path parameters, and headers. Automatically resolves parameter and '
                      'header values from store expressions.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **url** (String, required): The endpoint URL to fetch data from\n'
                      '- **queryParams** (UrlParameters, optional): Key-value pairs appended as query '
                      'string parameters to the URL\n'
                      '- **pathParams** (UrlParameters, optional): Key-value pairs substituted into '
                      'path placeholders in the URL\n'
                      '- **headers** (UrlParameters, optional): HTTP request headers\n'
                      '  - Default includes `Authorization` (from `LocalStore.AuthToken`) and '
                      '`clientCode` (from `Store.auth.loggedInClientCode`)\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful response\n'
                      '  - `data` (Any): The response body from the server\n'
                      '- **error**: Triggered on request failure\n'
                      '  - `data` (Any): Error response body\n'
                      '  - `headers` (Any): Error response headers\n'
                      '  - `status` (Number): HTTP status code\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Loading Page Data**: Fetch data to populate UI components on page load\n'
                      '- **Search and Filter**: Retrieve filtered results based on user input\n'
                      '- **API Integration**: Connect to REST APIs with automatic authentication\n'
                      '- **Data Refresh**: Re-fetch data to keep the UI up to date',
     'events': {'error': ['data', 'headers', 'status'], 'output': ['data']},
     'parameters': {'headers': {'hasDefault': True, 'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'pathParams': {'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'queryParams': {'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'url': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/FetchData.ts'},
    'GetStoreData': {'description': 'Retrieves data from the application store at a specified path',
     'documentation': '# UIEngine.GetStoreData\n'
                      '\n'
                      'Retrieves data from the application store at a specified path. Evaluates the '
                      'path using the expression context to resolve any dynamic references.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **path** (String, required): The store path to retrieve data from\n'
                      '  - Examples: `Store.user.name`, `Page.formData`, `LocalStore.AuthToken`\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered with the retrieved data\n'
                      '  - `data` (Any): The value found at the specified store path\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Data Access**: Read values from the store for conditional logic\n'
                      '- **Dynamic Expressions**: Retrieve data using dynamically constructed paths\n'
                      '- **Cross-Component Data**: Access data set by other components\n'
                      '- **Store Inspection**: Check current store values during workflow execution',
     'events': {'output': ['data']},
     'parameters': {'path': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/GetStoreData.ts'},
    'InitiateSocialLogin': {'description': 'Navigates to authzump social-login (Google/Meta) for the current or specified app',
     'documentation': '# UIEngine.InitiateSocialLogin\n'
                      '\n'
                      'Kicks off the SSO3 social-login flow by doing a top-level redirect to '
                      "authzump's social-register evoke endpoint. The user is taken through the OAuth "
                      "provider, and authzump's callback redirects them back to this app fully "
                      'authenticated via the chained `/sso/{token}` flow.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **platform** (String, required): `GOOGLE` or `META`\n'
                      '- **redirectUrl** (String, optional): Where to land after social login '
                      'completes. Defaults to the current page URL.\n'
                      '- **appCode** (String, optional): Override the target app code. Defaults to the '
                      'current app from `Store.application.appCode`.\n'
                      '- **clientCode** (String, optional): Override the target client code. Defaults '
                      "to the current app's client code or `SYSTEM`.\n"
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Fires after navigation is initiated\n'
                      '- **error**: Fires when SSO is not configured (no `__SSO_BEACON_HOST__` '
                      'injected) or no app code is available\n'
                      '\n'
                      '## Notes\n'
                      '\n'
                      'Requires `application.properties.sso3 === true` so that `IndexHTMLService` '
                      "injects the beacon host. If SSO isn't configured, this function emits an error "
                      'event without navigating.',
     'events': {'error': ['message']},
     'parameters': {'appCode': {'hasDefault': True, 'type': 'string'},
                    'clientCode': {'hasDefault': True, 'type': 'string'},
                    'platform': {'type': 'string'},
                    'redirectUrl': {'hasDefault': True, 'type': 'string'}},
     'source': 'ui-app/client/src/functions/InitiateSocialLogin.ts'},
    'Login': {'description': 'Authenticates a user and stores session data in the application store',
     'documentation': '# UIEngine.Login\n'
                      '\n'
                      'Authenticates a user by calling the `/api/security/authenticate` endpoint. On '
                      'success, stores authentication data in `Store.auth`, saves the access token to '
                      '`LocalStore.AuthToken`, and clears all page caches to ensure a fresh session.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **userName** (String, required): Username or email for authentication\n'
                      "- **password** (String, optional, default: ''): User password\n"
                      '- **userId** (Any, optional, default: null): User ID if available\n'
                      "- **otp** (String, optional, default: ''): One-time password for two-factor "
                      'authentication\n'
                      "- **pin** (String, optional, default: ''): PIN code if required\n"
                      "- **identifierType** (String, optional, default: ''): Type of identifier being "
                      'used for login\n'
                      '- **rememberMe** (Boolean, optional, default: false): Whether to persist the '
                      'session\n'
                      '- **cookie** (Boolean, optional, default: false): Whether to set an '
                      'authentication cookie\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful authentication\n'
                      '  - `data` (Any): Authentication response containing access token and user '
                      'details\n'
                      '- **error**: Triggered on authentication failure\n'
                      '  - `data` (Any): Error response body\n'
                      '  - `headers` (Any): Error response headers\n'
                      '  - `status` (Number): HTTP status code\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **User Authentication**: Log users into the application\n'
                      '- **Multi-Factor Auth**: Support OTP and PIN-based authentication flows\n'
                      '- **Session Management**: Establish and persist user sessions\n'
                      '- **SSO Integration**: Authenticate via various identifier types',
     'events': {'error': ['data', 'headers', 'status'], 'output': ['data']},
     'parameters': {'cookie': {'hasDefault': True, 'type': 'boolean'},
                    'identifierType': {'hasDefault': True, 'type': 'string'},
                    'otp': {'hasDefault': True, 'type': 'string'},
                    'password': {'hasDefault': True, 'type': 'string'},
                    'pin': {'hasDefault': True, 'type': 'string'},
                    'rememberMe': {'hasDefault': True, 'type': 'boolean'},
                    'userId': {'hasDefault': True, 'type': 'any'},
                    'userName': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/Login.ts'},
    'Logout': {'description': 'Logs out the current user, clears session data, and optionally redirects',
     'documentation': '# UIEngine.Logout\n'
                      '\n'
                      'Logs out the current user by calling the `/api/security/revoke` endpoint. '
                      'Clears all authentication data from the store, removes the auth token from '
                      'local storage, and resets page caches. Optionally supports SSO logout and '
                      'post-logout redirection.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **ssoLogout** (Boolean, optional, default: false): Whether to perform SSO '
                      'logout in addition to local logout\n'
                      "- **redirectUrl** (String, optional, default: ''): URL to redirect to after "
                      'successful logout\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful logout\n'
                      '- **error**: Triggered on logout failure\n'
                      '  - `data` (Any): Error response body\n'
                      '  - `headers` (Any): Error response headers\n'
                      '  - `status` (Number): HTTP status code\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **User Sign Out**: End the user session and clear credentials\n'
                      '- **SSO Logout**: Sign out from both the app and the identity provider\n'
                      '- **Session Expiry**: Programmatically log out when a session expires\n'
                      '- **Security**: Force logout on suspicious activity',
     'events': {'error': ['data', 'headers', 'status']},
     'parameters': {'redirectUrl': {'hasDefault': True, 'type': 'string'},
                    'ssoLogout': {'hasDefault': True, 'type': 'boolean'}},
     'source': 'ui-app/client/src/functions/Logout.ts'},
    'Message': {'description': 'Displays a notification message to the user with configurable type and scope',
     'documentation': '# UIEngine.Message\n'
                      '\n'
                      "Adds a notification message to the application's message queue. Messages can be "
                      'displayed globally or scoped to a specific page. Supports different message '
                      'types for various severity levels.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **msg** (Any, required): The message content to display\n'
                      '- **isGlobalScope** (Boolean, optional, default: true): If true, the message is '
                      'shown globally; if false, scoped to a specific page\n'
                      "- **pageName** (String, optional, default: '__GLOBAL__'): The page name for "
                      'page-scoped messages\n'
                      "- **type** (String, optional, default: 'ERROR'): Message severity type\n"
                      '  - `ERROR`: Error notification (red)\n'
                      '  - `WARNING`: Warning notification (yellow/orange)\n'
                      '  - `INFO`: Informational notification (blue)\n'
                      '  - `SUCCESS`: Success notification (green)\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after the message is added to the queue\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Form Validation Feedback**: Show errors when form validation fails\n'
                      '- **Operation Confirmation**: Confirm successful save, delete, or update '
                      'operations\n'
                      '- **API Error Display**: Show user-friendly error messages from API failures\n'
                      '- **Warnings**: Alert users about potential issues or required actions',
     'events': {},
     'parameters': {'isGlobalScope': {'hasDefault': True, 'type': 'boolean'},
                    'msg': {'type': 'any'},
                    'pageName': {'hasDefault': True, 'type': 'string'},
                    'type': {'hasDefault': True, 'type': 'string'}},
     'source': 'ui-app/client/src/functions/Message.ts'},
    'Navigate': {'description': 'Navigates to a specified URL or page path within the application',
     'documentation': '# UIEngine.Navigate\n'
                      '\n'
                      'Navigates to a specified URL or internal page path. For internal links with '
                      '`_self` target, uses the History API for seamless SPA navigation. For external '
                      'links or other targets, uses `window.open`. Supports removing the current page '
                      'from browser history.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **linkPath** (String, required): The URL or page path to navigate to\n'
                      "- **target** (String, optional, default: '_self'): Window target (`_self`, "
                      '`_blank`, `_parent`, `_top`)\n'
                      '- **force** (Boolean, optional, default: false): If true, forces a full '
                      'navigation even for internal links\n'
                      '- **removeThisPageFromHistory** (Boolean, optional, default: false): If true, '
                      'replaces the current history entry instead of pushing a new one\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after navigation is initiated\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Page Navigation**: Move between pages in the application\n'
                      '- **External Links**: Open external URLs in new tabs\n'
                      '- **Post-Login Redirect**: Navigate to a target page after authentication\n'
                      '- **Wizard Flows**: Navigate between steps, optionally preventing back '
                      'navigation\n'
                      '- **Deep Linking**: Navigate to specific pages with parameters',
     'events': {},
     'parameters': {'force': {'hasDefault': True, 'type': 'boolean'},
                    'linkPath': {'type': 'string'},
                    'removeThisPageFromHistory': {'hasDefault': True, 'type': 'boolean'},
                    'target': {'hasDefault': True, 'type': 'string'}},
     'source': 'ui-app/client/src/functions/Navigate.ts'},
    'NavigateBack': {'description': 'Navigates to the previous page in browser history',
     'documentation': '# UIEngine.NavigateBack\n'
                      '\n'
                      'Navigates to the previous page in the browser history by calling '
                      '`window.history.back()`. Equivalent to the user clicking the browser back '
                      'button.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      'None\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after navigation is initiated\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Cancel Actions**: Return to the previous page when the user cancels an '
                      'operation\n'
                      '- **Back Navigation**: Provide in-app back button functionality\n'
                      '- **Form Cancellation**: Navigate away from a form without saving',
     'events': {},
     'parameters': {},
     'source': 'ui-app/client/src/functions/NavigateBack.ts'},
    'NavigateForward': {'description': 'Navigates to the next page in browser history',
     'documentation': '# UIEngine.NavigateForward\n'
                      '\n'
                      'Navigates to the next page in the browser history by calling '
                      '`window.history.forward()`. Equivalent to the user clicking the browser forward '
                      'button. Only works if the user has previously navigated back.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      'None\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after navigation is initiated\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Forward Navigation**: Provide in-app forward button functionality\n'
                      '- **Redo Navigation**: Return to a page after going back\n'
                      '- **Navigation Controls**: Build custom browser-like navigation controls',
     'events': {},
     'parameters': {},
     'source': 'ui-app/client/src/functions/NavigateForward.ts'},
    'OpenWindow': {'description': 'Opens a URL in a new browser window or tab with configurable features',
     'documentation': '# UIEngine.OpenWindow\n'
                      '\n'
                      'Opens a URL in a new browser window or tab using `window.open()`. Supports '
                      'configuring the target, window features (size, position, etc.), and popup '
                      'mode.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **url** (String, required): The URL to open\n'
                      "- **target** (String, optional, default: '_blank'): Window target (`_blank`, "
                      '`_self`, `_parent`, `_top`, or a named window)\n'
                      "- **features** (String, optional, default: ''): Window features string (e.g., "
                      '`width=800,height=600,scrollbars=yes`)\n'
                      '- **popup** (Boolean, optional, default: false): If true, adds `popup=yes` to '
                      'the window features\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after the window is opened\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **External Links**: Open external websites in new tabs\n'
                      '- **Preview Windows**: Open preview or print views in popup windows\n'
                      '- **OAuth Flows**: Open authentication popups for third-party login\n'
                      '- **Documentation**: Open help or documentation pages in new tabs\n'
                      '- **Reports**: Open generated reports in separate windows',
     'events': {},
     'parameters': {'features': {'hasDefault': True, 'type': 'string'},
                    'popup': {'hasDefault': True, 'type': 'boolean'},
                    'target': {'hasDefault': True, 'type': 'string'},
                    'url': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/OpenWindow.ts'},
    'QueryAnalytics': {'description': 'Runs an analytics query against PostHog through the tenant-scoped backend proxy.',
     'documentation': '# UIEngine.QueryAnalytics\n'
                      '\n'
                      'Forwards a HogQL (or other PostHog query envelope) to '
                      '`/api/ui/analytics/query`. The backend enforces tenant scoping — every query is '
                      'filtered by `app_code` and `url_client_code` server-side, regardless of what '
                      'the body contains.\n'
                      '\n'
                      'Caller must supply `appCode` and `clientCode`. The authenticated user must have '
                      'write access to the application and their own client must own or manage the '
                      'requested `clientCode` (same rules as deleting an app).\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **appCode** (String, required): Application to scope the query to.\n'
                      '- **clientCode** (String, required): URL client code (tenant) to scope the '
                      'query to.\n'
                      '- **query** (Any, required): PostHog query envelope. Example: `{ kind: '
                      '"HogQLQuery", query: "SELECT count() FROM events WHERE event = \'$pageview\'" '
                      '}`. Supports `HogQLQuery`, `TrendsQuery`, `FunnelsQuery`, `RetentionQuery`, '
                      '`PathsQuery`, `LifecycleQuery`, `StickinessQuery`.\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on success.\n'
                      '  - `data` (Any): The PostHog response body.\n'
                      '- **error**: Triggered on failure.\n'
                      '  - `data` (Any): Error response body.\n'
                      '  - `status` (Number): HTTP status code.\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Drive AnalyticsQuery widget**: Bind the function to a widget that renders '
                      'the result.\n'
                      '- **Custom KPI panels**: Read a specific number into a counter or KPI tile.\n'
                      '- **Background metric refresh**: Run on a timer to keep dashboards live.',
     'events': {'error': ['data', 'status'], 'output': ['data']},
     'parameters': {'appCode': {'type': 'string'},
                    'clientCode': {'type': 'string'},
                    'query': {'type': 'any'}},
     'source': 'ui-app/client/src/functions/QueryAnalytics.ts'},
    'Refresh': {'description': 'Reloads the current page in the browser',
     'documentation': '# UIEngine.Refresh\n'
                      '\n'
                      'Reloads the current page by calling `window.location.reload()`. This performs a '
                      'full page reload, re-fetching all resources and re-initializing the '
                      'application.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      'None\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered before the page reload begins\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Force Refresh**: Reload the page after critical data changes\n'
                      '- **Error Recovery**: Attempt to recover from unexpected application states\n'
                      '- **Cache Clearing**: Force re-fetch of all resources after updates\n'
                      '- **Post-Update Reload**: Refresh after applying configuration changes',
     'events': {},
     'parameters': {},
     'source': 'ui-app/client/src/functions/Refresh.ts'},
    'ScrollTo': {'description': 'Scrolls the window to a specified vertical and horizontal position',
     'documentation': '# UIEngine.ScrollTo\n'
                      '\n'
                      'Scrolls the browser window to a specified position. Supports named positions '
                      '(top, bottom, left, right) or exact pixel values. The scroll behavior can be '
                      'instant or smooth.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      "- **vertical** (String, optional, default: 'top'): Vertical scroll position\n"
                      '  - `top`: Scroll to the top of the page\n'
                      '  - `bottom`: Scroll to the bottom of the page\n'
                      '  - Any numeric string (e.g., `"200"`): Scroll to that pixel offset from the '
                      'top\n'
                      "- **horizontal** (String, optional, default: 'left'): Horizontal scroll "
                      'position\n'
                      '  - `left`: Scroll to the left edge\n'
                      '  - `right`: Scroll to the right edge\n'
                      '  - Any numeric string (e.g., `"100"`): Scroll to that pixel offset from the '
                      'left\n'
                      "- **behaviour** (String, optional, default: 'Instant'): Scroll animation "
                      'behavior\n'
                      '  - `Instant`: Jump immediately to the position\n'
                      '  - `Smooth`: Animate smoothly to the position\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after the scroll operation\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Back to Top**: Scroll to the top of a long page\n'
                      '- **Form Focus**: Scroll to a form section after validation errors\n'
                      '- **Content Navigation**: Jump to specific sections on a page\n'
                      '- **Infinite Scroll**: Scroll to load more content positions',
     'events': {},
     'parameters': {'behaviour': {'hasDefault': True, 'type': 'string'},
                    'horizontal': {'hasDefault': True, 'type': 'string'},
                    'vertical': {'hasDefault': True, 'type': 'string'}},
     'source': 'ui-app/client/src/functions/ScrollTo.ts'},
    'ScrollToGrid': {'description': 'Scrolls a specific grid component into view by its element ID',
     'documentation': '# UIEngine.ScrollToGrid\n'
                      '\n'
                      'Scrolls a specific grid component into view using its element ID and the '
                      '`scrollIntoView` API. Useful for programmatically focusing on a data grid or '
                      'any element by its ID.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **gridkey** (String, required): The DOM element ID of the grid to scroll to\n'
                      "- **behaviour** (String, optional, default: 'Instant'): Scroll animation "
                      'behavior\n'
                      '  - `Instant`: Jump immediately to the element\n'
                      '  - `Smooth`: Animate smoothly to the element\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after the scroll operation\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Data Grid Focus**: Scroll to a specific data grid after filtering or '
                      'searching\n'
                      '- **Element Navigation**: Jump to any element by its ID\n'
                      '- **Form Sections**: Scroll to a specific section of a form\n'
                      '- **Error Highlighting**: Scroll to a component that has validation errors',
     'events': {},
     'parameters': {'behaviour': {'hasDefault': True, 'type': 'string'}, 'gridkey': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/ScrollToGrid.ts'},
    'SendData': {'description': 'Sends data to the server using a specified HTTP method with support for file '
                    'uploads and downloads',
     'documentation': '# UIEngine.SendData\n'
                      '\n'
                      'Makes an HTTP request with a specified method (POST, PUT, PATCH, etc.) and '
                      'payload. Automatically detects File objects in the payload and converts to '
                      'FormData for file uploads. Supports downloading the response as a file.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **url** (String, required): The endpoint URL to send data to\n'
                      '- **method** (String, required): HTTP method to use (e.g., POST, PUT, PATCH)\n'
                      '- **queryParams** (UrlParameters, optional): Key-value pairs appended as query '
                      'string parameters\n'
                      '- **pathParams** (UrlParameters, optional): Key-value pairs substituted into '
                      'path placeholders in the URL\n'
                      '- **payload** (Any, required): The request body data. If it contains File '
                      'objects, automatically converts to FormData\n'
                      '- **downloadAsAFile** (Boolean, optional, default: false): If true, downloads '
                      'the response as a file in the browser\n'
                      "- **downloadFileName** (String, optional, default: ''): Custom filename for the "
                      'downloaded file. Falls back to Content-Disposition header\n'
                      '- **headers** (UrlParameters, optional): HTTP request headers\n'
                      '  - Default includes `Authorization` (from `LocalStore.AuthToken`) and '
                      '`clientCode` (from `Store.auth.loggedInClientCode`)\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered on successful response\n'
                      '  - `data` (Any): The response body from the server\n'
                      '- **error**: Triggered on request failure\n'
                      '  - `data` (Any): Error response body\n'
                      '  - `headers` (Any): Error response headers\n'
                      '  - `status` (Number): HTTP status code\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Form Submission**: Submit form data to create or update records\n'
                      '- **File Upload**: Upload images, documents, or other files\n'
                      '- **File Download**: Generate and download reports, exports, or documents\n'
                      '- **API Integration**: Send data to external APIs with various HTTP methods\n'
                      '- **Bulk Operations**: Send batch update or create requests',
     'events': {'error': ['data', 'headers', 'status'], 'output': ['data']},
     'parameters': {'downloadAsAFile': {'hasDefault': True, 'type': 'boolean'},
                    'downloadFileName': {'hasDefault': True, 'type': 'string'},
                    'headers': {'hasDefault': True, 'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'method': {'type': 'string'},
                    'pathParams': {'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'payload': {'type': 'any'},
                    'queryParams': {'ref': 'UIEngine.UrlParameters', 'type': 'ref'},
                    'url': {'type': 'string'}},
     'source': 'ui-app/client/src/functions/SendData.ts'},
    'SetStore': {'description': 'Sets or deletes a value at a specified path in the application store',
     'documentation': '# UIEngine.SetStore\n'
                      '\n'
                      'Sets data at a specified path in the application store (Store, Page, or Parent '
                      'scope). Creates a deep copy of the value before storing to prevent unintended '
                      'reference mutations. Can also delete keys from the store.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **path** (String, required): The store path to set the value at\n'
                      '  - Examples: `Store.user.name`, `Page.formData.email`, `Parent.items`\n'
                      '  - Supports `Parent.` prefix for updating parent component store in nested '
                      'contexts\n'
                      '- **value** (Any, optional): The value to set at the specified path\n'
                      '- **deleteKey** (Boolean, optional, default: false): If true, deletes the key '
                      'at the path instead of setting a value\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after the store is updated\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Form State Management**: Update form field values in the store\n'
                      '- **User Session Data**: Store user preferences or session information\n'
                      '- **Component Communication**: Share data between components via the store\n'
                      '- **Reset State**: Clear or delete temporary data after processing\n'
                      '- **Parent Updates**: Update parent component state from child components',
     'events': {},
     'parameters': {'deleteKey': {'hasDefault': True, 'type': 'boolean'},
                    'path': {'type': 'string'},
                    'value': {'type': 'any'}},
     'source': 'ui-app/client/src/functions/SetStore.ts'},
    'ShortUniqueId': {'description': 'Generates a short unique identifier string',
     'documentation': '# UIEngine.ShortUniqueId\n'
                      '\n'
                      'Generates and returns a short unique identifier string. Useful for creating '
                      'unique keys, reference IDs, or temporary identifiers without server-side '
                      'generation.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      'None\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered with the generated ID\n'
                      '  - `id` (String): A short unique identifier string\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Unique Keys**: Generate keys for dynamic list items or components\n'
                      '- **Temporary IDs**: Create client-side IDs before server persistence\n'
                      '- **Correlation IDs**: Generate IDs to track related operations\n'
                      '- **Cache Busting**: Create unique suffixes for resource URLs',
     'events': {'output': ['id']},
     'parameters': {},
     'source': 'ui-app/client/src/functions/ShortUniqueId.ts'},
    'TrackAnalyticsEvent': {'description': 'Sends a named analytics event to PostHog with optional properties.',
     'documentation': '# UIEngine.TrackAnalyticsEvent\n'
                      '\n'
                      'Captures a named analytics event via the page-level PostHog client '
                      '(`window.posthog.capture`). The event is augmented with the super properties '
                      'already registered by the framework (`app_code`, `client_code`, '
                      '`url_client_code`, `page_name`).\n'
                      '\n'
                      'If analytics is disabled for the application, or the user has not opted in, the '
                      'call is a no-op.\n'
                      '\n'
                      '## Parameters\n'
                      '\n'
                      '- **eventName** (String, required): The event name to capture (e.g. '
                      '`checkout_started`, `cta_clicked`).\n'
                      '- **properties** (Any, optional): Object/Map of additional properties to attach '
                      'to the event.\n'
                      '\n'
                      '## Events\n'
                      '\n'
                      '- **output**: Triggered after the capture call (always — capture is '
                      'fire-and-forget).\n'
                      '\n'
                      '## Use Cases\n'
                      '\n'
                      '- **Funnel tracking**: Emit `signup_started`, `signup_completed`, '
                      '`checkout_completed` from event flows.\n'
                      '- **Feature instrumentation**: Tag specific KIRun-driven actions with stable '
                      'event names.\n'
                      '- **A/B test metrics**: Pair with feature flags to measure variant impact.',
     'events': {},
     'parameters': {'eventName': {'type': 'string'}, 'properties': {'hasDefault': True, 'type': 'any'}},
     'source': 'ui-app/client/src/functions/TrackAnalyticsEvent.ts'},
}
