from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class BusinessProfileInput(BaseModel):
    """Input payload containing scraped business details and campaign settings.
    
    This is passed to the MetaAudiencePlannerAgent to infer demographic suggestions.
    """
    businessType: str = Field(..., description="Broad category of the business (e.g., 'Real Estate', 'SaaS')")
    businessSummary: str = Field(..., description="Short summary/profile describing what the business does and sells")
    locations: Optional[List[str]] = Field(default=None, description="Confirmed or suggested geographical locations for ad targeting")
    prices: Optional[List[str]] = Field(default=None, description="Extracted price points of the business products/services")
    campaignObjective: Optional[str] = Field(default=None, description="Campaign marketing goal (e.g., 'LEADS', 'SALES', 'AWARENESS')")


class RecommendationDetail(BaseModel):
    """Specific demographic targeting recommendations."""
    ageMin: int = Field(..., description="Recommended minimum targeting age (typically 13-65)")
    ageMax: int = Field(..., description="Recommended maximum targeting age (typically 13-65)")
    gender: Literal["male", "female", "all"] = Field(..., description="Target gender strategy")


class MetaAudiencePlan(BaseModel):
    """Complete audience targeting plan generated by the LLM audience planner."""
    recommendation: RecommendationDetail = Field(..., description="Recommended demographic targets")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of the recommendation between 0.0 and 1.0")
    reasoning: List[str] = Field(..., description="Logical reasoning, persona details, and assumptions justifying recommendations")
