-- V1__Initial_AI_Tracking.sql
-- Initial schema for AI token tracking and session management
-- Note: Database is already selected by the connection pool

-- Sessions table - tracks AI generation sessions per page
CREATE TABLE IF NOT EXISTS `ai_tracking_sessions` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SESSION_ID` VARCHAR(64) NOT NULL COMMENT 'clientCode_pageName_shortUUID',
    `CLIENT_CODE` CHAR(8) NOT NULL,
    `CLIENT_ID` BIGINT UNSIGNED NOT NULL,
    `USER_ID` BIGINT UNSIGNED NOT NULL,
    `PAGE_NAME` VARCHAR(256) DEFAULT NULL,
    `APP_CODE` VARCHAR(64) DEFAULT NULL,
    `STATUS` ENUM('ACTIVE', 'COMPLETED', 'EXPIRED') DEFAULT 'ACTIVE',
    `TOTAL_INPUT_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `TOTAL_OUTPUT_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `TOTAL_CACHE_READ_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `TOTAL_CACHE_CREATION_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `REQUEST_COUNT` INT UNSIGNED DEFAULT 0,
    `TURN_COUNT` INT UNSIGNED DEFAULT 0 COMMENT 'Number of conversation turns',
    `CONTEXT_TOKENS_USED` BIGINT UNSIGNED DEFAULT 0 COMMENT 'Current context size in tokens',
    `CONTEXT_LIMIT` BIGINT UNSIGNED DEFAULT 184000 COMMENT 'Model context limit (default 200K - 16K reserved)',
    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL,
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` BIGINT UNSIGNED DEFAULT NULL,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SESSION_ID` (`SESSION_ID`),
    INDEX `IDX_CLIENT_USER` (`CLIENT_ID`, `USER_ID`),
    INDEX `IDX_CLIENT_CODE` (`CLIENT_CODE`),
    INDEX `IDX_STATUS` (`STATUS`),
    INDEX `IDX_CREATED_AT` (`CREATED_AT`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Token usage records table - tracks individual LLM calls
CREATE TABLE IF NOT EXISTS `ai_tracking_token_usage` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SESSION_ID` VARCHAR(64) NOT NULL,
    `REQUEST_ID` VARCHAR(64) NOT NULL,
    `CLIENT_CODE` CHAR(8) NOT NULL,
    `CLIENT_ID` BIGINT UNSIGNED NOT NULL,
    `USER_ID` BIGINT UNSIGNED NOT NULL,
    `AGENT_TYPE` VARCHAR(32) NOT NULL COMMENT 'Layout, Component, Events, Styles, Animation, Data, Review',
    `MODEL` VARCHAR(64) NOT NULL,
    `LLM_PROVIDER` VARCHAR(32) NOT NULL COMMENT 'anthropic, openai',
    `INPUT_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `OUTPUT_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `CACHE_READ_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `CACHE_CREATION_TOKENS` BIGINT UNSIGNED DEFAULT 0,
    `LATENCY_MS` INT UNSIGNED DEFAULT NULL,
    `SUCCESS` TINYINT(1) DEFAULT 1,
    `ERROR_MESSAGE` TEXT DEFAULT NULL,
    `CREATED_BY` BIGINT UNSIGNED DEFAULT NULL,
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` BIGINT UNSIGNED DEFAULT NULL,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    INDEX `IDX_SESSION` (`SESSION_ID`),
    INDEX `IDX_REQUEST` (`REQUEST_ID`),
    INDEX `IDX_CLIENT_USER` (`CLIENT_ID`, `USER_ID`),
    INDEX `IDX_AGENT` (`AGENT_TYPE`),
    INDEX `IDX_CREATED_AT` (`CREATED_AT`),
    CONSTRAINT `FK_USAGE_SESSION` FOREIGN KEY (`SESSION_ID`)
        REFERENCES `ai_tracking_sessions` (`SESSION_ID`) ON DELETE CASCADE
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Conversation history table - stores turns for multi-turn context
CREATE TABLE IF NOT EXISTS `ai_session_history` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SESSION_ID` VARCHAR(64) NOT NULL,
    `REQUEST_ID` VARCHAR(64) NOT NULL,
    `TURN_NUMBER` INT UNSIGNED NOT NULL COMMENT 'Sequential turn in conversation (1, 2, 3...)',
    `USER_INSTRUCTION` TEXT NOT NULL COMMENT 'User prompt/instruction',
    `ASSISTANT_SUMMARY` TEXT DEFAULT NULL COMMENT 'Summary of what was generated/changed',
    `PAGE_SNAPSHOT` LONGTEXT DEFAULT NULL COMMENT 'JSON snapshot of page after this turn (for context)',
    `INPUT_TOKENS_USED` BIGINT UNSIGNED DEFAULT 0 COMMENT 'Tokens used for context in this turn',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    INDEX `IDX_SESSION` (`SESSION_ID`),
    INDEX `IDX_TURN` (`SESSION_ID`, `TURN_NUMBER`),
    CONSTRAINT `FK_HISTORY_SESSION` FOREIGN KEY (`SESSION_ID`)
        REFERENCES `ai_tracking_sessions` (`SESSION_ID`) ON DELETE CASCADE
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Migration tracking table - tracks applied migrations (Flyway-style)
CREATE TABLE IF NOT EXISTS `ai_tracking_migrations` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `VERSION` VARCHAR(50) NOT NULL,
    `DESCRIPTION` VARCHAR(200) NOT NULL,
    `APPLIED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_VERSION` (`VERSION`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
