"""Component catalog — fetches and caches component metadata.

The catalog is generated by nocode-ui's CI pipeline from component
source files (*Properties.ts, *StyleProperties.ts) and deployed
to CDN as component-catalog.json.

nocode-ai fetches this catalog at startup and makes it available
to the agent's system prompt, so the agent knows valid properties
per component type.

For development (when no CDN catalog is available), falls back to
a minimal built-in catalog derived from the aicontext docs.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)


class ComponentCatalog:
    """Fetches and caches the component catalog."""

    def __init__(self, catalog_url: str = "") -> None:
        self.catalog_url = catalog_url
        self._catalog: dict[str, Any] | None = None

    async def load(self) -> bool:
        """Fetch catalog from CDN. Returns True if loaded successfully."""
        if not self.catalog_url:
            logger.info("No catalog URL configured, using fallback catalog")
            self._catalog = _FALLBACK_CATALOG
            return True

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.get(self.catalog_url)
                resp.raise_for_status()
                self._catalog = resp.json()
                component_count = len(self._catalog.get("components", {}))
                logger.info(f"Loaded component catalog: {component_count} components from {self.catalog_url}")
                return True
        except Exception as e:
            logger.warning(f"Failed to load catalog from CDN: {e}. Using fallback.")
            self._catalog = _FALLBACK_CATALOG
            return False

    def get_component_info(self, component_type: str) -> dict[str, Any]:
        """Get property definitions for a component type."""
        if not self._catalog:
            return {}
        return self._catalog.get("components", {}).get(component_type, {})

    def get_all_types(self) -> list[str]:
        """List all available component types."""
        if not self._catalog:
            return []
        return list(self._catalog.get("components", {}).keys())

    def to_prompt_context(self) -> str:
        """Format catalog as concise text for system prompt injection.

        Returns a summary of all component types with descriptions,
        visual structure, properties, sub-components, and theme style info.
        """
        if not self._catalog:
            return ""

        components = self._catalog.get("components", {})
        if not components:
            return ""

        lines = ["## Component Catalog\n"]
        lines.append(f"Available types ({len(components)}): {', '.join(sorted(components.keys()))}\n")

        # Design type reference
        dt_descs = self._catalog.get("designTypeDescriptions", {})
        if dt_descs:
            lines.append("### Design Type Reference")
            for dt_name, dt_desc in dt_descs.items():
                lines.append(f"- **{dt_name}**: {dt_desc}")
            lines.append("")

        for comp_type, info in sorted(components.items()):
            description = info.get("description", "")
            lines.append(f"### {comp_type}")
            if description:
                lines.append(description)

            # Visual structure
            structure = info.get("structure")
            if structure:
                lines.append(f"Structure: `{structure}`")

            # Properties
            props = info.get("properties", [])
            if props:
                prop_names = [p.get("name", "?") for p in props[:20]]
                lines.append(f"Properties: {', '.join(prop_names)}")

                # Show enum values for key properties
                for p in props:
                    enum_vals = p.get("enumValues", [])
                    if enum_vals:
                        names = [e.get("name", "?") for e in enum_vals]
                        lines.append(f"  {p['name']}: {names}")

            # Sub-components (stylable parts)
            sub_comps = info.get("subComponents", {})
            if sub_comps and len(sub_comps) > 1:
                parts = []
                for key, sub_info in sub_comps.items():
                    if key == "(root)":
                        continue
                    desc = sub_info.get("description", key)
                    parts.append(f"{key} ({desc})")
                if parts:
                    lines.append(f"Stylable parts: {', '.join(parts)}")

            # Theme style info (design types)
            theme = info.get("themeStyleProperties", {})
            if theme:
                design_types = theme.get("designTypes", [])
                if design_types:
                    lines.append(f"Design types: {', '.join(design_types)}")

            lines.append("")

        return "\n".join(lines)


# ── Fallback catalog ────────────────────────────────────────────
# Minimal catalog for development when no CDN catalog is available.
# Covers the most common component types from aicontext/22-component-reference.md.

_FALLBACK_CATALOG: dict[str, Any] = {
    "version": "fallback",
    "components": {
        "Grid": {
            "properties": [
                {"name": "columns", "type": "number"},
                {"name": "columnGap", "type": "string"},
                {"name": "rowGap", "type": "string"},
                {"name": "direction", "type": "string", "enum": ["ROW", "COLUMN"]},
            ],
            "styleProperties": [],
        },
        "Flex": {
            "properties": [
                {"name": "direction", "type": "string", "enum": ["ROW", "COLUMN", "ROW_REVERSE", "COLUMN_REVERSE"]},
                {"name": "wrap", "type": "string", "enum": ["WRAP", "NOWRAP", "WRAP_REVERSE"]},
                {"name": "justifyContent", "type": "string"},
                {"name": "alignItems", "type": "string"},
                {"name": "gap", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Text": {
            "properties": [
                {"name": "text", "type": "string"},
                {"name": "textType", "type": "string", "enum": ["H1", "H2", "H3", "H4", "H5", "H6", "PARAGRAPH", "SPAN"]},
            ],
            "styleProperties": [],
        },
        "Button": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "onClick", "type": "string"},
                {"name": "designType", "type": "string", "enum": ["_outlined", "_text", "_iconButton", "_fabButton", "_decorative"]},
                {"name": "colorScheme", "type": "string"},
                {"name": "leftIcon", "type": "string"},
                {"name": "rightIcon", "type": "string"},
            ],
            "styleProperties": [],
        },
        "TextBox": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "placeholder", "type": "string"},
                {"name": "bindingPath", "type": "string"},
                {"name": "validation", "type": "object"},
                {"name": "designType", "type": "string"},
            ],
            "styleProperties": [],
        },
        "TextArea": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "placeholder", "type": "string"},
                {"name": "bindingPath", "type": "string"},
                {"name": "rows", "type": "number"},
            ],
            "styleProperties": [],
        },
        "Image": {
            "properties": [
                {"name": "src", "type": "string"},
                {"name": "alt", "type": "string"},
                {"name": "onClick", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Icon": {
            "properties": [
                {"name": "icon", "type": "string"},
                {"name": "size", "type": "number"},
                {"name": "onClick", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Dropdown": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "bindingPath", "type": "string"},
                {"name": "dataBinding", "type": "object"},
                {"name": "labelKey", "type": "string"},
                {"name": "valueKey", "type": "string"},
            ],
            "styleProperties": [],
        },
        "CheckBox": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "bindingPath", "type": "string"},
                {"name": "onClick", "type": "string"},
            ],
            "styleProperties": [],
        },
        "RadioButton": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "bindingPath", "type": "string"},
                {"name": "dataBinding", "type": "object"},
            ],
            "styleProperties": [],
        },
        "ToggleButton": {
            "properties": [
                {"name": "label", "type": "string"},
                {"name": "bindingPath", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Calendar": {
            "properties": [
                {"name": "bindingPath", "type": "string"},
                {"name": "dateFormat", "type": "string"},
                {"name": "minDate", "type": "string"},
                {"name": "maxDate", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Table": {
            "properties": [
                {"name": "dataBinding", "type": "object"},
                {"name": "columns", "type": "array"},
                {"name": "pagination", "type": "boolean"},
                {"name": "pageSize", "type": "number"},
            ],
            "styleProperties": [],
        },
        "Tabs": {
            "properties": [
                {"name": "tabs", "type": "array"},
                {"name": "defaultTab", "type": "number"},
                {"name": "orientation", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Stepper": {
            "properties": [
                {"name": "steps", "type": "array"},
                {"name": "currentStep", "type": "number"},
                {"name": "orientation", "type": "string"},
            ],
            "styleProperties": [],
        },
        "Menu": {
            "properties": [
                {"name": "menuItems", "type": "array"},
                {"name": "orientation", "type": "string", "enum": ["HORIZONTAL", "VERTICAL"]},
            ],
            "styleProperties": [],
        },
    },
}
