FUNCTION on_Load
    LOGIC
        setStore7: UIEngine.SetStore(path = "Page.ongoingPurchase", value = false)
        setStore8: UIEngine.SetStore(path = "Page.activePurchase", value = false)
        setStore24: UIEngine.SetStore(path = "Page.isClickedViewTransaction", value = true)
            output
                setStore16: UIEngine.SetStore(path = "Page.cancelBookingIndex", value = "") AFTER Steps.setStore24.output
                    output
                        setStore17: UIEngine.SetStore(path = "Page.changeUnitIndex", value = "") AFTER Steps.setStore16.output
                            output
                                setStore15: UIEngine.SetStore(path = "Page.count", value = 1) AFTER Steps.setStore17.output
                                    output
                                        setStore13: UIEngine.SetStore(path = "Page.isClickedCancel", value = false) AFTER Steps.setStore15.output
                                            output
                                                setStore14: UIEngine.SetStore(path = "Page.currentIndex", value = "") AFTER Steps.setStore13.output
                                                    output
                                                        setStore11: UIEngine.SetStore(path = "Page.monthThreeChar", value = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]) AFTER Steps.setStore14.output
                                                            output
                                                                setStore12: UIEngine.SetStore(path = "Page.DaySuffixArray", value = ["01st", "02nd", "03rd", "04th", "05th", "06th", "07th", "08th", "09th", "10th", "11th", "12th", "13th", "14th", "15th", "16th", "17th", "18th", "19th", "20th", "21st", "22nd", "23rd", "24th", "25th", "26th", "27th", "28th", "29th", "30th", "31st"]) AFTER Steps.setStore11.output
                                                                    output
                                                                        setStore5: UIEngine.SetStore(path = "Page.showSpinner", value = true) AFTER Steps.setStore12.output
                                                                            output
                                                                                if8: System.If(condition = Url.pathParts[1]) AFTER Steps.totalAmount.output, Steps.setStore5.output
                                                                                    true
                                                                                        getBookingDetailsByProjectId: rim.getBookingDetailsByProjectId(projectId = Url.pathParts[1]) AFTER Steps.if8.true
                                                                                            output
                                                                                                BookingDetails: UIEngine.SetStore(path = "Page.bookingDetails", value = Steps.getBookingDetailsByProjectId.output.individualBookings)
                                                                                    false
                                                                                        getBookingDetails: rim.getBookingDetails() AFTER Steps.if8.false
                                                                                            output
                                                                                                BookingDetails_Copy_1: UIEngine.SetStore(path = "Page.bookingDetails", value = Steps.getBookingDetails.output.bookingDetails.content)
                                                                                    output
                                                                                        Projects: UIEngine.SetStore(path = "Page.projects", value = {}) AFTER Steps.if8.output
                                                                                            output
                                                                                                KYCs: UIEngine.SetStore(path = "Page.kycs", value = {}) AFTER Steps.Projects.output
                                                                                                    output
                                                                                                        setStore: UIEngine.SetStore(path = "Page.activeBookingDetails", value = []) AFTER Steps.KYCs.output
                                                                                                            output
                                                                                                                setStore1: UIEngine.SetStore(path = "Page.ongoingBookingDetails", value = []) AFTER Steps.setStore.output
                                                                                                                    output
                                                                                                                        bookingDetailsLoop: System.Loop.ForEachLoop(source = Page.bookingDetails) AFTER Steps.setStore1.output
                                                                                                                            iteration
                                                                                                                                if: System.If(condition = `Steps.bookingDetailsLoop.iteration.each.purchaseStatus = "Active"`)
                                                                                                                                    true
                                                                                                                                        addingEachAmountInvested: UIEngine.SetStore(path = "Page.totalInvestmentAmount", value = Page.totalInvestmentAmount + {{Steps.bookingDetailsLoop.iteration.each.amountInvested}}) AFTER Steps.if.true
                                                                                                                                        insertLast: System.Array.InsertLast(source = Page.activeBookingDetails, element = Steps.bookingDetailsLoop.iteration.each) AFTER Steps.if.true
                                                                                                                                            output
                                                                                                                                                setStore2: UIEngine.SetStore(path = "Page.activeBookingDetails", value = Steps.insertLast.output.result)
                                                                                                                                if_Copy_1: System.If(condition = `Steps.bookingDetailsLoop.iteration.each.purchaseStatus = "Ongoing"`)
                                                                                                                                    true
                                                                                                                                        insertLast1: System.Array.InsertLast(source = Page.ongoingBookingDetails, element = Steps.bookingDetailsLoop.iteration.each) AFTER Steps.if_Copy_1.true
                                                                                                                                            output
                                                                                                                                                setStore3: UIEngine.SetStore(path = "Page.ongoingBookingDetails", value = Steps.insertLast1.output.result)
                                                                                                                                if2: System.If(condition = Steps.bookingDetailsLoop.iteration.each.kycAccountId)
                                                                                                                                    true
                                                                                                                                        checkingKycId: System.If(condition = Page.kycs.{{Steps.bookingDetailsLoop.iteration.each.kycAccountId}}) AFTER Steps.if2.true
                                                                                                                                            false
                                                                                                                                                eachKycObject: UIEngine.SetStore(path = `'Page.kycs.{{Steps.bookingDetailsLoop.iteration.each.kycAccountId}}'`, value = {}) AFTER Steps.checkingKycId.false
                                                                                                                                checkingProjectId: System.If(condition = Page.projects.{{Steps.bookingDetailsLoop.iteration.each.projectId}})
                                                                                                                                    false
                                                                                                                                        eachProjectObject: UIEngine.SetStore(path = `'Page.projects.{{Steps.bookingDetailsLoop.iteration.each.projectId}}'`, value = {}) AFTER Steps.checkingProjectId.false
                                                                                                                                if5_Copy_1: System.If(condition = Steps.bookingDetailsLoop.iteration.each.unitDetails.phaseId and Steps.bookingDetailsLoop.iteration.each.unitDetails.phaseId != undefined)
                                                                                                                                    true
                                                                                                                                        if6_Copy_1: System.If(condition = Page.phaseDetails.{{Steps.bookingDetailsLoop.iteration.each.unitDetails.phaseId}}) AFTER Steps.if5_Copy_1.true
                                                                                                                                            false
                                                                                                                                                setStore_Copy_1_Copy_1: UIEngine.SetStore(path = `'Page.phaseDetails.{{Steps.bookingDetailsLoop.iteration.each.unitDetails.phaseId}}'`, value = {}) AFTER Steps.if6_Copy_1.false
                                                                                                                                if5_Copy_1_Copy_1: System.If(condition = Steps.bookingDetailsLoop.iteration.each.unitDetails.towerId and Steps.bookingDetailsLoop.iteration.each.unitDetails.towerId != undefined)
                                                                                                                                    true
                                                                                                                                        if6_Copy_1_Copy_1: System.If(condition = Page.towerDetails.{{Steps.bookingDetailsLoop.iteration.each.unitDetails.towerId }}) AFTER Steps.if5_Copy_1_Copy_1.true
                                                                                                                                            false
                                                                                                                                                setStore_Copy_1_Copy_1_Copy_1: UIEngine.SetStore(path = `'Page.towerDetails.{{Steps.bookingDetailsLoop.iteration.each.unitDetails.towerId}}'`, value = {}) AFTER Steps.if6_Copy_1_Copy_1.false
                                                                                                                                if5_Copy_1_Copy_1_Copy_1: System.If(condition = Steps.bookingDetailsLoop.iteration.each.unitDetails.blockId and Steps.bookingDetailsLoop.iteration.each.unitDetails.blockId != undefined)
                                                                                                                                    true
                                                                                                                                        if6_Copy_1_Copy_1_Copy_1: System.If(condition = Page.blockDetails.{{Steps.bookingDetailsLoop.iteration.each.unitDetails.blockId }}) AFTER Steps.if5_Copy_1_Copy_1_Copy_1.true
                                                                                                                                            false
                                                                                                                                                setStore_Copy_1_Copy_1_Copy_1_Copy_1: UIEngine.SetStore(path = `'Page.blockDetails.{{Steps.bookingDetailsLoop.iteration.each.unitDetails.blockId }}'`, value = {}) AFTER Steps.if6_Copy_1_Copy_1_Copy_1.false
                                                                                                                                if5: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].isRefundcredited = true)
                                                                                                                                    true
                                                                                                                                        setStore20: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingStatusCount'`, value = 3) AFTER Steps.if5.true
                                                                                                                                    false
                                                                                                                                        if6: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingCancel.salesPerson.cancelRequest = true) AFTER Steps.if5.false
                                                                                                                                            true
                                                                                                                                                setStore21: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingStatusCount'`, value = 2) AFTER Steps.if6.true
                                                                                                                                            false
                                                                                                                                                if7: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingCancel.customer.cancelRequest = true) AFTER Steps.if6.false
                                                                                                                                                    true
                                                                                                                                                        setStore22: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingStatusCount'`, value = 1) AFTER Steps.if7.true
                                                                                                                                                    false
                                                                                                                                                        setStore23: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingStatusCount'`, value = 1) AFTER Steps.if7.false
                                                                                                                                if1: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingDate)
                                                                                                                                    true
                                                                                                                                        split: System.String.Split(string = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingDate, searchString = `'/'`) AFTER Steps.if1.true
                                                                                                                                            output
                                                                                                                                                setStore10: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].DateMonthYear'`, value = Steps.split.output.result)
                                                                                                                                if3: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingCancel.customer.cancelRequestDate)
                                                                                                                                    true
                                                                                                                                        split1: System.String.Split(string = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingCancel.customer.cancelRequestDate, searchString = "/") AFTER Steps.if3.true
                                                                                                                                            output
                                                                                                                                                setStore18: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingCancel.customer.DateMonthYear'`, value = Steps.split1.output.result)
                                                                                                                                if4: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingUnitChange.changeUnitRequestDate)
                                                                                                                                    true
                                                                                                                                        split2: System.String.Split(string = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingUnitChange.changeUnitRequestDate, searchString = "/") AFTER Steps.if4.true
                                                                                                                                            output
                                                                                                                                                setStore19: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingUnitChange.DateMonthYear'`, value = Steps.split2.output.result)
                                                                                                                                if4_Copy_1: System.If(condition = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingUnitRequest.unitRequestedDate)
                                                                                                                                    true
                                                                                                                                        split3: System.String.Split(string = Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingUnitRequest.unitRequestedDate, searchString = "/") AFTER Steps.if4_Copy_1.true
                                                                                                                                            output
                                                                                                                                                setStore19_Copy_1: UIEngine.SetStore(path = `'Page.bookingDetails[{{Steps.bookingDetailsLoop.iteration.index}}].bookingUnitRequest.DateMonthYear'`, value = Steps.split3.output.result)
                                                                                                                            output
                                                                                                                                kycKeys: System.Object.ObjectKeys(source = Page.kycs) AFTER Steps.bookingDetailsLoop.output
                                                                                                                                    output
                                                                                                                                        kycKeysLoop: System.Loop.ForEachLoop(source = Steps.kycKeys.output.value)
                                                                                                                                            iteration
                                                                                                                                                getSingleKYC: kyc.getSingleKYC(kycId = Steps.kycKeysLoop.iteration.each)
                                                                                                                                                    error
                                                                                                                                                        kycErrorMessage: UIEngine.Message(msg = Steps.getSingleKYC.error.message)
                                                                                                                                                    output
                                                                                                                                                        sendingDetailstokycs: UIEngine.SetStore(path = `'Page.kycs.{{Steps.kycKeysLoop.iteration.each}}'`, value = Steps.getSingleKYC.output.kycDetails)
                                                                                                                                            output
                                                                                                                                                projectKeys: System.Object.ObjectKeys(source = Page.projects) AFTER Steps.kycKeysLoop.output
                                                                                                                                                    output
                                                                                                                                                        projectKeysLoop: System.Loop.ForEachLoop(source = Steps.projectKeys.output.value)
                                                                                                                                                            iteration
                                                                                                                                                                projectDetails: CoreServices.Storage.Read(dataObjectId = Steps.projectKeysLoop.iteration.each, appCode = "rim", storageName = "Project")
                                                                                                                                                                    error
                                                                                                                                                                        message: UIEngine.Message(msg = Steps.projectDetails.error.result)
                                                                                                                                                                    output
                                                                                                                                                                        SendingDetailstoprojects: UIEngine.SetStore(path = `'Page.projects.{{Steps.projectKeysLoop.iteration.each}}'`, value = Steps.projectDetails.output.result)
                                                                                                                                                            output
                                                                                                                                                                phaseKeys: System.Object.ObjectKeys(source = Page.phaseDetails) AFTER Steps.projectKeysLoop.output
                                                                                                                                                                    output
                                                                                                                                                                        phaseKeysLoop: System.Loop.ForEachLoop(source = Steps.phaseKeys.output.value)
                                                                                                                                                                            iteration
                                                                                                                                                                                phaseDetails: CoreServices.Storage.Read(dataObjectId = Steps.phaseKeysLoop.iteration.each, appCode = "rim", storageName = "Phase")
                                                                                                                                                                                    error
                                                                                                                                                                                        messagePhse: UIEngine.Message(msg = Steps.phaseDetails.error.result)
                                                                                                                                                                                    output
                                                                                                                                                                                        SendingDetailstophase: UIEngine.SetStore(path = `'Page.phaseDetails.{{Steps.phaseKeysLoop.iteration.each}}'`, value = Steps.phaseDetails.output.result)
                                                                                                                                                                            output
                                                                                                                                                                                towerKeys: System.Object.ObjectKeys(source = Page.towerDetails) AFTER Steps.phaseKeysLoop.output
                                                                                                                                                                                    output
                                                                                                                                                                                        towerKeysLoop: System.Loop.ForEachLoop(source = Steps.towerKeys.output.value)
                                                                                                                                                                                            iteration
                                                                                                                                                                                                towerDetails: CoreServices.Storage.Read(dataObjectId = Steps.towerKeysLoop.iteration.each, appCode = "rim", storageName = "Tower")
                                                                                                                                                                                                    error
                                                                                                                                                                                                        message_Tower: UIEngine.Message(msg = Steps.towerDetails.error.result)
                                                                                                                                                                                                    output
                                                                                                                                                                                                        SendingDetailstotowers: UIEngine.SetStore(path = `'Page.towerDetails.{{Steps.towerKeysLoop.iteration.each}}'`, value = Steps.towerDetails.output.result)
                                                                                                                                                                                            output
                                                                                                                                                                                                blockKeys: System.Object.ObjectKeys(source = Page.blockDetails) AFTER Steps.towerKeysLoop.output
                                                                                                                                                                                                    output
                                                                                                                                                                                                        blockKeysLoop: System.Loop.ForEachLoop(source = Steps.blockKeys.output.value)
                                                                                                                                                                                                            iteration
                                                                                                                                                                                                                blockDetails: CoreServices.Storage.Read(dataObjectId = Steps.blockKeysLoop.iteration.each, appCode = "rim", storageName = "Block")
                                                                                                                                                                                                                    error
                                                                                                                                                                                                                        message_BLock: UIEngine.Message(msg = Steps.blockDetails.error.result)
                                                                                                                                                                                                                    output
                                                                                                                                                                                                                        SendingDetailstoBlock: UIEngine.SetStore(path = `'Page.blockDetails.{{Steps.blockKeysLoop.iteration.each}}'`, value = Steps.blockDetails.output.result)
                                                                                                                                                                                                            output
                                                                                                                                                                                                                setStore4: UIEngine.SetStore(path = "Page.show", value = `Page.bookingDetails.length = 0 ? 'emptyGrid' : 'showProjects'`) AFTER Steps.blockKeysLoop.output
                                                                                                                                                                                                                    output
                                                                                                                                                                                                                        setStore9: UIEngine.SetStore(path = "Page.showSpinner", value = `false`) AFTER Steps.setStore4.output
                                                                                        checkingAmountPaid: _.checkingAmountPaid() AFTER Steps.if8.output
        businessDetails: _.businessDetails()
        setStore25: UIEngine.SetStore(path = `'Url.pathParts[0]'`, value = "/customerDashboard")
            output
                totalAmount: UIEngine.SetStore(path = "Page.totalInvestmentAmount", value = 0) AFTER Steps.setStore25.output